import asyncio, time
from playwright.async_api import async_playwright
async def main():
    async with async_playwright() as p:
        b=await p.chromium.connect_over_cdp("http://127.0.0.1:9222")
        pg=await b.contexts[0].new_page()
        pg.on("pageerror", lambda e: print("PAGEERR", e))
        await pg.set_viewport_size({"width":390,"height":800})
        await pg.goto("file:///F:/APP%20BY%20HOANG/HOC%20TIENG%20ANH/index.html?v="+str(int(time.time())))
        await asyncio.sleep(1.2)
        await pg.evaluate("localStorage.removeItem('bhta_profile'); localStorage.setItem('bhta_cfg', JSON.stringify({voice:'matilda',rate:0.9,theme:'green'}))")
        await pg.reload(); await asyncio.sleep(1.5)
        await pg.screenshot(path="dist/v3_setup.png")
        await pg.evaluate("localStorage.setItem('bhta_profile', JSON.stringify({name:'Su',mascot:'cat',setup:true}))")
        await pg.reload(); await asyncio.sleep(1.5)
        await pg.click(".topic >> nth=1"); await asyncio.sleep(1.2)
        await pg.screenshot(path="dist/v3_learn.png")
        await pg.click(".mode[data-nav=play]"); await asyncio.sleep(0.8)
        for g in ["bubble","truefalse","memory","missing","draw"]:
            await pg.click(".gtile[data-g=%s]" % g); await asyncio.sleep(2.8 if g=="missing" else 1.4)
            await pg.screenshot(path="dist/v3_%s.png" % g)
            await pg.click(".mode[data-nav=play]"); await asyncio.sleep(0.8)
        await pg.click("#back"); await asyncio.sleep(0.8)
        await pg.click(".topic >> nth=2"); await asyncio.sleep(1.2)
        await pg.screenshot(path="dist/v3_colors.png")
        await pg.click("#back"); await asyncio.sleep(0.8)
        await pg.click(".topic >> nth=3"); await asyncio.sleep(1.2)
        await pg.screenshot(path="dist/v3_numbers.png")
        await pg.close(); print("ok")
asyncio.run(main())
